apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-app
  template:
    metadata:
      labels:
        app: crud-app
    spec:
      containers:
      - name: crud-app
        image: s223743838/crud-microservice:latest 
        ports:
        - containerPort: 3008
        env:
        - name: MONGO_URI
          value: mongodb+srv://s223743838:password-123@cluster0.gpmpazp.mongodb.net/ITEM?retryWrites=true&w=majority&appName=Cluster0
